[package]
name = "xtask-prelude"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.58"
env_logger = "0.9.0"
log = "0.4.17"
# tracing = { version = "0.1.35", features = ["attributes"] }
# tracing-subscriber = { version = "0.3.11", features = ["env-filter"] }
